before_script:
  - mysql -e 'create database myzoom_test;'
before_install:
  - mysql -e "create database IF NOT EXISTS myzoom_test;" -uroot -ptoor
env:
  - DB=mysql
language: ruby
rvm:
  - 2.2.1
addons:
  code_climate:
    repo_token: 321e1df96aed3f5b70952b96d871946e15467ca97a19c551e111e2c13c10ec92
