# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa1d128dd1198f0852ca667075e4784034404f2a3c96f72447a5671f31f0824abae01928bec9e94bfbcd2b1892191cb41c183555926f1a683312ca4820c2938a

test:
  secret_key_base: efe6d4c696c49af33ff63637c8bdece9ca86c0904507b578387c7dbfdda877b7655384bc3e8ae33fa0050731f8a00ca9579b79079a8285a88429e018a2fb61f5

localenvironment:
  secret_key_base: efe6d4c696c49af33ff63637c8bdece9ca86c0904507b578387c7dbfdda877b7655384bc3e8ae33fa0050731f8a00ca9579b79079a8285a88429e018a2fb61f5


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
